name: CI/CD Pipeline- Test python script

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@master

            - name: Setup up python
              uses: actions/setup-python@v3
              with:
                python-version: 3.10.12

            - name: Install dependencies
              run: pip3 install -r requirements.txt

            - name: Run tests
              run: pytest
